loadtest:
  server-address: ${SERVER_HOST:localhost}
  server-port: ${SERVER_PORT:8001}
  think-behavior: human

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:faf-java-server}
    password: ${DB_PASSWORD:banana}
    url: ${DB_URL:jdbc:mysql://localhost:3306/faf?useSSL=false}

logging:
  level:
    org.springframework: warn
    com.faforever.loadtest.server.client.ClientSimulator: trace
    com.faforever.loadtest.server.runner.LoadTestRunner: warn

